### ISSUE TITLE
 Error when inserting article: B & B1005

### ISSUE THREAD

**Issue by nitaipanda** [moloni/magento2#4] opened 2019-08-21 10:32 UTC
when we create invoice from admin by moloni then show error.where is this problem.

![image](https://user-images.githubusercontent.com/20333565/63424888-02240c00-c42d-11e9-9575-4cde63eb5964.png)

**Comment by nitaipanda** [comment] 2019-08-21 10:36
please check this issues and give solution as soon as possible.

**Comment by moloni-pt** [comment] 2019-08-21 12:12
Hello, can you click on the console log and check out the request being made to the endpoint products/insert?

**Comment by moloni-pt** [comment] 2019-08-29 09:16
Duplicate of #5

**Closed as completed** 2019-08-29 09:16 UTC
